server:
  port: 9001

spring:
  spring:
    profiles: prod
  datasource:
    url: jdbc:mysql://mysql-standalone:3306/jpatutorial?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true